#!/usr/bin/env node
/**
 * Lists the art that exists on disk, so the app can tell a product's own drawing
 * from a product that has none yet.
 *
 *   pnpm art:index
 *
 * Writes src/features/studio/model/art-index.json: every PNG in
 * public/assets/studio, by name, sorted.
 *
 * The app cannot read the filesystem — the catalog model runs in the browser —
 * so the folder listing is committed alongside the art. `pnpm dev` and
 * `pnpm build` regenerate it first, and `art.test.ts` fails if the committed
 * index has drifted from the folder.
 */

import { readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ART_DIR = resolve(ROOT, "public/assets/studio");
const OUT = resolve(ROOT, "src/features/studio/model/art-index.json");

const files = await readdir(ART_DIR);

const names = files
  .filter((file) => file.endsWith(".png"))
  .map((file) => file.slice(0, -".png".length))
  .sort();

await writeFile(
  OUT,
  `${JSON.stringify(
    {
      note: "Generated by pnpm art:index. Every PNG in public/assets/studio.",
      names,
    },
    null,
    2,
  )}\n`,
);

process.stdout.write(`Indexed ${names.length} drawings from ${ART_DIR}\n`);
